### ISSUE TITLE
Having a collaboration between lynt and eslint-config-unobtrusive

### ISSUE THREAD

**Issue by suchipi** [saadq/lynt#1]
Hi there!

I'm glad to see this repo. I think non-formatting linters are great and am glad to see more development in that space.

I'm the creator and maintainer of https://github.com/suchipi/eslint-config-unobtrusive, an eslint config with goals very similar to this project's.

If there is any way we could collaborate, I would be happy to contribute :) no pressure though

**Comment by olstenlarck** [comment]
Actually, is there ESLint config that disables all style rules? Probably we should create one, so it can be applied to any other configs, so such tools like that can only use the rest of the rules of some style.

**Comment by suchipi** [comment]
@olstenlarck https://github.com/prettier/eslint-config-prettier is such a config

**Comment by olstenlarck** [comment]
Yea, but not sure if it disables all the style rules available, or only these that may/might conflict with Prettier.

**Comment by saadq** [comment]
Hey guys, and thanks @suchipi for opening this issue. I have seen you pretty often in Prettier issues, so I'm thankful for your work.

 I took a look at your repo and I do agree with most of the goals – I think Lynt can be uphold its own goals better by following the goals of `unobtrusive` and removing a few rules that I still have like `curly`. 

There are some aspects of your goals that I'm uncertain about introducing with `lynt` though, like making a distinction between `warn` and `error`. With this project, I had opted in to treating each rule as an `error` for simplicity and I'm of the opinion that having both warnings/errors makes it seem like the warnings are less important to fix. I guess I felt that the lack of stylistic rules should just mean that any linting errors that do show up should just be considered to be an `error`.

So currently, the [ESLint rules](https://github.com/saadq/lynt/blob/master/src/eslint/config.ts#L11) and [TSLint rules](https://github.com/saadq/lynt/blob/master/src/tslint/config.ts#L11) are hardcoded. My plan had been to remove the hardcoded stuff and just use an `extends` and create the following packages:

* `eslint-config-lynt`
* `eslint-config-lynt-react`
* `eslint-config-lynt-flow`
* `tslint-config-lynt`
* `tslint-config-lynt-react`

I had been planning on creating a GitHub org for this (maybe something like `lyntjs`) and then moving everything to `lyntjs/lynt`, `lyntjs/eslint-config-lynt`, etc.

If you would be interested, perhaps you could be added as a collaborator on the github org and `eslint-config-unobtrusive` could be used for `lyntjs/eslint-config-lynt`, `unobtrusive/flowtype` could be `lyntjs/eslint-config-lynt-flow`, etc. We can look at any difference in rules and discuss them. As for the TSLint stuff, we could just create them as new packages.

Let me know if you'd be open to doing this. Also @olstenlarck, I would be happy to have your feedback on rules as well. I have seen you pretty active in the `standard` community back when I used it, so would be happy to hear your comments on rules.

**Comment by suchipi** [comment]
@saadq Sounds good to me. Since eslint configs are just objects, it would not be too difficult for `lynt/eslint-config-lynt` to iterate over the rules in `eslint-config-unobtrusive` and change the `"warn"`s to `"error"`s- I've done this before to get warnings to fail in [jest-runner-eslint](https://www.npmjs.com/package/jest-runner-eslint).

**Comment by saadq** [comment]
@suchipi Hey, I've been looking at `eslint-config-unobtrusive` some more and I'm starting to think that the project's goals might be too different. So my main goal for this project was to be an error-checker + best practice enforcer. The rules I wanted to avoid were basically just the ones in [this section](https://eslint.org/docs/rules/#stylistic-issues).

Some examples of rules that `eslint-config-unobtrusive` allows that I don't think would be compatible with `lynt` are:

* curly
* eqeqeq
* radix

I know that I previously mentioned that turning off the `curly` rules in `lynt` would be a good idea, but I'm not sure I'm on board with it anymore. One of the main goals for this project was to be very beginner-friendly and to try to help new developers with possible errors. I've been working part time as a Codecademy advisor where I review a lot of code, and I have seen numerous issues with missing curly braces in `if` blocks with multiple statements and issues with `==` instead of `===`. 

I realize that you were trying to be extremely unimposing (or I guess _unobtrusive_ :)) with your project where you were solely focusing on likely errors, but I think with `lynt` I was trying to be a bit more opinionated in regards to best-practices. 

Let me know if you'd be open to changing the views of your project, though I doubt you would want to. In this case, I think it may be simpler just to create `eslint-config-lynt` as its own thing instead of mapping over your object and adding/removing/changing rules. 

Either way, I'd still be happy to have you as a collaborator if you'd still want to.

**Comment by saadq** [comment]
@suchipi On second thought, I don't think there would be much complexity with using `eslint-config-unobtrusive` as a base, and then just layering some changes on top. Let me know if you'd be okay with that or if you'r prefer `lynt` to just use its own config in that case.

**Comment by suchipi** [comment]
I think it would be easier to maintain if `lynt` used its own config in that case- otherwise you would have to look in two places to understand the rules, and every change in eslint-config-unobtrusive would be a potentially breaking change.

**Comment by suchipi** [comment]
I'm gonna go ahead and close this. Thanks for talking through it!
