### ISSUE TITLE
30 high severity vulnerabilities in 2466 scanned packages

### ISSUE THREAD

**Issue by naomijub** [saadq/lynt#45]
Running `npm audit --registry=https://registry.npmjs.org` I got 30 high severity vulnerabilities in lynt packages. Is it possible to upgrade them?

This are the libs that should be updated:
set-value   >= 3.0.1
mixin-deep  >=2.0.1

**Comment by saadq** [comment]
I have been pretty inactive as of late with this project, which is what led to the deps being outdated for awhile. I'll make a post about why I've been inactive later, but the project is definitely not dead and is currently undergoing a rewrite. It'll probably be a bit more time before I release it though.

At the very least, for now I can look into upgrading the existing dependencies for the current version of lynt so that these vulnerabilities wont exist. Hopefully I can get to that this weekend

**Comment by naomijub** [comment]
Thanks!

**Comment by saadq** [comment]
Sorry, wasn't able to get to it this weekend, should be able to get to it tomorrow or the day after.
